### PR TITLE
cleaned up and fixed proper documentation for react default readme files

### PR DESCRIPTION
**Pull request by TylerSowers**
in the newest documentation that period does not exist

### CODE REVIEW

**Comment by Tolterix** [comment]
My team has felt the impact of leaving periods in their README files. This is real world life saving.

**Review by Eyegee-Eleven — CHANGES_REQUESTED** [review]
Please consider the fact that our team is enthusiastic. While a period would suffice in this situation, its a team standard to use exclamation whenever possible to show enthusiasm and emphasis of our instructions.

**Comment by TylerSowers** [comment]
I have made requested changes thanks for the guidance and insight on how you and your team operates.

**Comment by ghost** [comment]
Me as a user, however was very mislead. The instructions became unclear and my phallus became jammed in a white circular ventilator.

**Review by Eyegee-Eleven — CHANGES_REQUESTED** [review]
Due to user confusion & standardization across the project, I will have to ask you to apply the exclamation to all statements in the ReadMe!

**Pull request closed without merging**
